import type { Metadata } from 'next'
import './globals.css'
import Header from './_layout-components/Header'
import Footer from './_layout-components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="h-screen w-screen min-w-[980]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
